# Generated by Django 6.1.1 on 2026-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytask',
            options={'verbose_name': 'Kategoriyalar', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Vazifalar', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categorytask',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi ...'),
        ),
    ]
